#!/bin/sh -e

COUNT=0
SUM=0

for VAL in `find /sys/devices/system/cpu -name scaling_cur_freq -exec cat {} \;`; do
	COUNT=$((${COUNT}+1))
	SUM=$((${SUM}+${VAL}))
done

if [ ${COUNT} -eq 0 -o ${SUM} -eq 0 ]; then
	/bin/echo -n "no cpufreq"
	exit 1
fi

FREQ=`echo ${SUM} ${COUNT} | awk '{ printf "%.1f", $1 / 1000000 / $2; }'`

/bin/echo -n "cpu: ${FREQ} GHz"

